# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iamjhu
owner: Johnny Hu
email: jgeehen.hu@gmail.com
copyright: Copyright &copy; 2016 iamjhu. All rights reserved.
description: > # this means to ignore newlines until "baseurl:"
  A financial professional turned web developer-in-training. 
  Follow Johnny as he attempts to code, debug, and program his
  way to becoming a full-stack web developerâ€”blogging about it 
  as he goes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.iamjhu.com" # the base hostname & protocol for your site
github_username:  iamjhu
linkedin_username: jgeehenhu
facebook_username: jhu1986
twitter_username: iamjhu
instagram_username: jhuphotos

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "iamjhu"
      category: ["blog", "ruby"]
      tags: ["ruby", "coding", "programming", "tech"]

